### ISSUE TITLE
déconnexion et pas de musique 

### ISSUE THREAD

**Issue by kaunar-de-renard** [BlackScarx/DiscordMusicPlayer#11]
Bonjour,
  je ne sais pas si tu mets encore le logiciel à jour ( au vu de la date de la dernière maj).
De notre côté avec mon groupe d'amis on utilise le logiciel pour faire nos JDR à distance (très pratique pour le MJ).
Depuis quelques années déjà, le bot ne fonctionne plus. Il se deco-reco de manière aléatoire et ne prend plus en compte les fichiers mp3 qu'on lui donne.

Je crée le ticket sans trop d'espoir, mais si un jour tu passes par la je voudrais te remerciez pour ton travail qui nous aura permis pendant quelques années  de pouvoir nous amusez et faire des nuits blanches lors de nos séances.
bonne continuation pour la suite  ! 
(mais au fond de moi j'espère tout de même un correctif un jour ;( )

**Comment by BlackScarx** [comment]
Salut, j'ai posté une maj
https://github.com/BlackScarx/DiscordMusicPlayer/releases/tag/3.5.0
J'éspère que les problèmes seront résolu. J'ai pas eu le temps de tout testé mais de mon côté j'avais plus de problème à part avec les lives youtube qui se coupe tout seul. Mettre la playlist en repeat permet de contourner le problème.
Je te souhaite une bonne journée.

**Comment by kaunar-de-renard** [comment]
tout fonctionne a nouveau merci beaucoup !!!
