### ISSUE TITLE
Ability to double click songs in the list

### ISSUE THREAD

**Issue by burridgedan** [BlackScarx/DiscordMusicPlayer#2]
Hi,

I just started using the application and I must say it's PERFECT for my needs however, a suggestion I do have is the ability to click on the song in the playlist and have it play, but also keeping it in the playlist for later use. 

The latter issue isn't such a problem though as I can just set the playlist to repeat.

**Comment by BlackScarx** [comment]
https://github.com/BlackScarx/DiscordMusicPlayer/releases/tag/3.5.0
