### ISSUE TITLE
Impossible de lire des vidéos YouTube

### ISSUE THREAD

**Issue by 1dk-Why** [BlackScarx/DiscordMusicPlayer#3]
J'arrive à chercher des vidéos, les ajouter, mais, au moment de la lecture, elle disparaît, son nom n’apparaît plus. On dirait que le logiciel l'a ignoré.
J'arrive par contre à lire des fichiers locaux.

**Comment by BlackScarx** [comment]
https://github.com/BlackScarx/DiscordMusicPlayer/releases/tag/3.4.5
