### ISSUE TITLE
Déconnexions intermittentes du bot

### ISSUE THREAD

**Issue by EtienneSafa** [BlackScarx/DiscordMusicPlayer#7]
Salut !
Tout d'abord merci beaucoup pour cette initiative, c'est super !

J'ai un soucis de déconnexions intermittentes du bot dont je n'arrive pas à comprendre la cause.
Je ne connais pas encore bien Discord, j'ai essayé de regarder si ça pouvait venir des permissions mais j'ai du mal à comprendre dans l'ensemble.

**Comment by BlackScarx** [comment]
https://github.com/BlackScarx/DiscordMusicPlayer/releases/tag/3.5.0
