### ISSUE TITLE
Unable to play music

### ISSUE THREAD

**Issue by p43j77** [BlackScarx/DiscordMusicPlayer#8]
Hi
I have encountered some issues with the Player.
Any time I try to play music after the bot joined discord, the playlist will clear itself and the playback bar will show the name for a second then back in to "No music yet". No music will play at all (Youtube URL, FLAC won't work and MP3 won't show up on the playlist).
Also, every time I start the player, it will pin the GPU usage at about 20%. Not sure if the issues are related.
Great player tho, hope the issue will be fixed soon.

**Comment by BlackScarx** [comment]
https://github.com/BlackScarx/DiscordMusicPlayer/releases/tag/3.5.0
